/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-05-27 16:00:31 UTC)
 * on 2016-07-27 at 17:51:58 UTC 
 * Modify at your own risk.
 */

package com.appspot.justin_katzwhite_resume.resume;

/**
 * Service definition for Resume (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ResumeRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Resume extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.22.0 of the resume library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://justin-katzwhite-resume.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "resume/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Resume(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Resume(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the List collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Resume resume = new Resume(...);}
   *   {@code Resume.List.List request = resume.list().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public List list() {
    return new List();
  }

  /**
   * The "list" collection of methods.
   */
  public class List {

    /**
     * Create a request for the method "list.bI".
     *
     * This request holds the parameters needed by the resume server.  After setting any optional
     * parameters, call the {@link BI#execute()} method to invoke the remote operation.
     *
     * @return the request
     */
    public BI bI() throws java.io.IOException {
      BI result = new BI();
      initialize(result);
      return result;
    }

    public class BI extends ResumeRequest<com.appspot.justin_katzwhite_resume.resume.model.ResumeData> {

      private static final String REST_PATH = "bi";

      /**
       * Create a request for the method "list.bI".
       *
       * This request holds the parameters needed by the the resume server.  After setting any optional
       * parameters, call the {@link BI#execute()} method to invoke the remote operation. <p> {@link
       * BI#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must be
       * called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @since 1.13
       */
      protected BI() {
        super(Resume.this, "GET", REST_PATH, null, com.appspot.justin_katzwhite_resume.resume.model.ResumeData.class);
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public BI setAlt(java.lang.String alt) {
        return (BI) super.setAlt(alt);
      }

      @Override
      public BI setFields(java.lang.String fields) {
        return (BI) super.setFields(fields);
      }

      @Override
      public BI setKey(java.lang.String key) {
        return (BI) super.setKey(key);
      }

      @Override
      public BI setOauthToken(java.lang.String oauthToken) {
        return (BI) super.setOauthToken(oauthToken);
      }

      @Override
      public BI setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (BI) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public BI setQuotaUser(java.lang.String quotaUser) {
        return (BI) super.setQuotaUser(quotaUser);
      }

      @Override
      public BI setUserIp(java.lang.String userIp) {
        return (BI) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.String text;

      /**

       */
      public java.lang.String getText() {
        return text;
      }

      public BI setText(java.lang.String text) {
        this.text = text;
        return this;
      }

      @Override
      public BI set(String parameterName, Object value) {
        return (BI) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "list.pL".
     *
     * This request holds the parameters needed by the resume server.  After setting any optional
     * parameters, call the {@link PL#execute()} method to invoke the remote operation.
     *
     * @param text
     * @return the request
     */
    public PL pL(java.lang.String text) throws java.io.IOException {
      PL result = new PL(text);
      initialize(result);
      return result;
    }

    public class PL extends ResumeRequest<com.appspot.justin_katzwhite_resume.resume.model.ResumeData> {

      private static final String REST_PATH = "pl/{text}";

      /**
       * Create a request for the method "list.pL".
       *
       * This request holds the parameters needed by the the resume server.  After setting any optional
       * parameters, call the {@link PL#execute()} method to invoke the remote operation. <p> {@link
       * PL#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must be
       * called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param text
       * @since 1.13
       */
      protected PL(java.lang.String text) {
        super(Resume.this, "GET", REST_PATH, null, com.appspot.justin_katzwhite_resume.resume.model.ResumeData.class);
        this.text = com.google.api.client.util.Preconditions.checkNotNull(text, "Required parameter text must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public PL setAlt(java.lang.String alt) {
        return (PL) super.setAlt(alt);
      }

      @Override
      public PL setFields(java.lang.String fields) {
        return (PL) super.setFields(fields);
      }

      @Override
      public PL setKey(java.lang.String key) {
        return (PL) super.setKey(key);
      }

      @Override
      public PL setOauthToken(java.lang.String oauthToken) {
        return (PL) super.setOauthToken(oauthToken);
      }

      @Override
      public PL setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (PL) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public PL setQuotaUser(java.lang.String quotaUser) {
        return (PL) super.setQuotaUser(quotaUser);
      }

      @Override
      public PL setUserIp(java.lang.String userIp) {
        return (PL) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.String text;

      /**

       */
      public java.lang.String getText() {
        return text;
      }

      public PL setText(java.lang.String text) {
        this.text = text;
        return this;
      }

      @Override
      public PL set(String parameterName, Object value) {
        return (PL) super.set(parameterName, value);
      }
    }

  }

  /**
   * Builder for {@link Resume}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Resume}. */
    @Override
    public Resume build() {
      return new Resume(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ResumeRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setResumeRequestInitializer(
        ResumeRequestInitializer resumeRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(resumeRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
